title: Schoen & Dangerous
email: zorpalopod@gmail.com
description: >-
  Personal blog about technology, life and everything in between.
baseurl: "/techblog"
url: "https://ewa-schoen.github.io"
github_username: ewa-schoen

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

port: 4001